<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fiberServiceCreationResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="xs:string" minOccurs="0"/>
        <xs:element name="<cyfunction Comment at 0x7ed83e5c9910>" type="xs:string" minOccurs="0"/>
        <xs:element name="category" type="xs:string" minOccurs="0"/>
        <xs:element name="<cyfunction Comment at 0x7ed83e5c9910>" type="xs:string" minOccurs="0"/>
        <xs:element name="state" type="xs:string" minOccurs="0"/>
        <xs:element name="orderDate" type="xs:string" minOccurs="0"/>
        <xs:element name="<cyfunction Comment at 0x7ed83e5c9910>" type="xs:string" minOccurs="0"/>
        <xs:element name="requestedCompletionDate" type="xs:string" minOccurs="0"/>
        <xs:element name="<cyfunction Comment at 0x7ed83e5c9910>" type="xs:string" minOccurs="0"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="<cyfunction Comment at 0x7ed83e5c9910>" type="xs:string" minOccurs="0"/>
        <xs:element name="id" type="xs:string" minOccurs="0"/>
        <xs:element name="status" type="xs:string" minOccurs="0"/>
        <xs:element name="feasibilityId" type="xs:string" minOccurs="0"/>
        <xs:element name="hardware" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="splitter" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="fiberCable" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="length" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="civilWorkExecution" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="manhole" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>