[metadata]
name = intservices
version = 0.1.0

[options]
packages = find:
install_requires = 
    fastapi>=0.111
    uvicorn[standard]>=0.30
    pydantic>=2.7
    pydantic-settings>=2.3
    httpx>=0.27
    sqlmodel>=0.0.16
    alembic>=1.13
    asyncpg>=0.29
    python-multipart>=0.0.9
    email-validator>=2.1
    orjson>=3.10
    python-jose[cryptography]>=3.3.0
    passlib[bcrypt]>=1.7.4
include_package_data = True
